### PR TITLE
dev: fix use of `fold` to get the first element of `starknet_contract_address` 🥷 

### LINKED ISSUE #166: dev: remove `fold` where possible
Remove the use of `fold` where we are using it to get the first index of a `Vec<FieldElement>`. This is bad practice and should be replaced with another method (could be `get(index)` for example).

Below example of the use of `fold`:
https://github.com/kkrt-labs/kakarot-rpc/blob/main/crates/core/src/client/mod.rs#L220
```[tasklist]
### Tasks
- [ ] Find all incorrect instances of the use of `fold`
- [ ] Decide and update to more idiomatic solition
```

### PR DESCRIPTION
**Pull request by bajpai244**
We were using `fold` on the `starknet_contract_address` vector, it is supposed to contain just one field element and that should be the contract address itself, we were using a concatenation technique to query the first value.

It also meant that if the length of this vector is 2 or something else than 1, then we won't be able to catch it, and will keep on concatenating!

The PR adds a better way to do this:
- to check for the length of this Vec  { and report in case there is some error in inspection }
- to query the first element
- shadow the same old variable so that we have a meaningful name for this value

Closes #166 

# Pull Request type

Please check the type of change your PR introduces:

- [ ] Bugfix
- [ ] Feature
- [ ] Code style update (formatting, renaming)
- [x] Refactoring (no functional changes, no API changes)
- [ ] Build-related changes
- [ ] Documentation content changes
- [ ] Testing
- [ ] Other (please describe):

# What is the current behavior?

We are using `fold` to obtain the first value of the `starknet_contract_address` vector, which is not the ideal way to do it.

Issue Number: #166 

# What is the new behavior?

We check for the first value of the `starknet_contract_address` vector in a better way, and also report an error if any in `starknet_contract_address`.

# Does this introduce a breaking change?

- [ ] Yes
- [x] No

### CODE REVIEW

File: crates/core/src/client/mod.rs [hunk 1]
```diff
@@ -216,14 +216,26 @@ impl KakarotClient for KakarotClientImpl {
...
+            return Err(KakarotClientError::OtherError(anyhow::anyhow!(
+                "Kakarot get_code: starknet_contract_address length is not 1"
+            )));
+        };
+
+        // shadow the variable to FielElement from a Vec<FieldElement>, for use in subsequent code
+        let starknet_contract_address = match starknet_contract_address.get(0) {
+            Some(x) => *x,
+            None => {
+                return Err(KakarotClientError::OtherError(anyhow::anyhow!(
```
Comment (greged93) [inline crates/core/src/client/mod.rs:230]: This feels weird because you should never reach this arm since you already checked that `starknet_contract_address.len() == 1`. Maybe something like:
```
        let starknet_contract_address = match starknet_contract_address.get(0) {
            Some(x) if starknet_contract_address.len() == 1 => *x,
            _ => {
                return Err(KakarotClientError::OtherError(anyhow::anyhow!(
                      "Kakarot get_code: starknet_contract_address length is not 1"
                )));
            }
        };
```

**Review by greged93 — COMMENTED** [review]
Just one comment

File: crates/core/src/client/mod.rs (hunk 1 above)
Comment (bajpai244) [reply crates/core/src/client/mod.rs:230]: Hello @greged93, I do not completely get this.

So, in match the other possible case is anyways `None`, so how is `_` better here { I see the point if there were multiple other possibilities for this value, then the above syntax feels like, "for anything else, let's throw error"  }

Is this some rust best practice to use, when other statements of match should not be reachable?

Comment (greged93) [reply crates/core/src/client/mod.rs:230]: No no, what I mean is that you checked the length of your array in the `if` condition. So you're kind of checking the length twice. I would remove the if and update with what I sent. What do you think?

Comment (bajpai244) [reply crates/core/src/client/mod.rs:230]: Oh! Now I get it makes sense!

Thanks, this is cleaner :)

Comment (bajpai244) [reply crates/core/src/client/mod.rs:224]: done [here](https://github.com/kkrt-labs/kakarot-rpc/pull/168/commits/2ee183d9fc761fa0dbf61fafed56b0641a8de6fb).

Comment (bajpai244) [reply crates/core/src/client/mod.rs:208]: rebased on main as well.

**Review by Eikix — APPROVED** [review]
lgtm 🔥
